name: mujoco-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - etils==1.12.2
      - Farama-Notifications==0.0.4
      - filelock==3.18.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - glfw==2.9.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - importlib_resources==6.5.2
      - Jinja2==3.1.6
      - kiwisolver==1.4.8
      - MarkupSafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mujoco==3.2.3
      - networkx==3.4.2
      - numpy==2.2.6
      - numpy-stl==3.2.0
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - PyOpenGL==3.1.9
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytz==2025.2
      - six==1.17.0
      - stable_baselines3==2.6.0
      - sympy==1.14.0
      - torch==2.7.1
      - typing_extensions==4.14.0
      - tzdata==2025.2
      - zipp==3.23.0
